In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("../Data/Processed_loan_approval_data.csv")

In [4]:
df.head()

,Applicant_Income,Coapplicant_Income,Age,Dependents,Existing_Loans,Savings,Loan_Amount,Loan_Term,Education_Level,Loan_Approved,...,Property_Area_Semiurban,Property_Area_Urban,Gender_Male,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed,Collateral_Ratio,DTI_Ratio_sq,Credit_Score_sq
0,109100.0,66100.0,51.0,1.0,5.0,61300.0,254000.0,48.0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.098421,0.209764,537289.0
1,10500.0,6800.0,43.0,4.0,1.0,3800.0,647000.0,60.0,0,0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.491495,0.147456,224676.0
2,22400.0,11500.0,23.0,2.0,2.0,4100.0,13600000.0,180.0,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.779412,0.363609,284089.0
3,10000.0,6300.0,45.0,2.0,5.0,134700.0,1806000.0,60.0,1,1,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,2.052601,0.080089,546121.0
4,10000.0,4600.0,40.0,2.0,2.0,1000.0,3090000.0,120.0,1,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.352427,0.100489,312481.0

# Train-Test-Split + Feature Scaling

In [5]:
X = df.drop("Loan_Approved", axis=1)
y = df["Loan_Approved"]

In [6]:
y.head()

0    0
1    0
2    0
3    1
4    0
Name: Loan_Approved, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
X_test.head()

,Applicant_Income,Coapplicant_Income,Age,Dependents,Existing_Loans,Savings,Loan_Amount,Loan_Term,Education_Level,Employment_Status_Salaried,...,Property_Area_Semiurban,Property_Area_Urban,Gender_Male,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed,Collateral_Ratio,DTI_Ratio_sq,Credit_Score_sq
607262,22100.0,5200.0,31.0,2.0,4.0,11600.0,846000.0,36.0,1,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.764773,0.335241,386884.0
688057,71900.0,21000.0,46.0,1.0,2.0,49200.0,13518000.0,48.0,0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.863145,0.050176,450241.0
599549,57000.0,9800.0,47.0,1.0,4.0,24300.0,10201000.0,36.0,0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.473777,0.012769,419904.0
423542,18400.0,6400.0,49.0,1.0,3.0,6600.0,15154000.0,6.0,0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.816352,0.017424,404496.0
167381,296500.0,160300.0,36.0,1.0,3.0,1105500.0,1707000.0,24.0,1,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.385470,0.098596,553536.0

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
X_test_scaled

array([[-0.52920549, -0.48333255, -0.74699587, ...,  0.71912147,
         1.36023033, -0.33264932],
       [-0.1983138 , -0.26874049,  0.81755456, ..., -0.53086033,
        -0.70808304,  0.25436513],
       [-0.29731553, -0.42085638,  0.92185792, ..., -1.0706654 ,
        -0.97949271, -0.02671285],
       ...,
       [-0.16642063, -0.13292274,  0.50464448, ...,  0.88012549,
        -0.684974  ,  0.45567911],
       [-0.13784966, -0.27009867,  0.81755456, ...,  1.21680258,
        -0.54711788,  1.51920212],
       [-0.02555911,  0.45924267, -0.43408578, ...,  0.23983551,
         0.38408568,  0.05779492]])

# Train & Evaluate Models

In [11]:
# Logistic regression

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

log_model = LogisticRegression()
log_model.fit(X_train_scaled, y_train)

y_pred = log_model.predict(X_test_scaled)

# Evaluation
print("Logistic Regression Model")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("F1 score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("CM: ", confusion_matrix(y_test, y_pred))

Logistic Regression Model
Precision:  0.7478846347100794
Recall:  0.6461252626278412
F1 score:  0.6932908538743875
Accuracy:  0.8312973970075835
CM:  [[125025  12544]
 [ 20380  37211]]

In [12]:
# KNN Not suitable for large number of features 

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=7)
knn_model.fit(X_train_scaled, y_train)

y_pred = knn_model.predict(X_test_scaled)

# Evaluation
print("KNN Model")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("F1 score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("CM: ", confusion_matrix(y_test, y_pred))

c:\Users\mayan\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "c:\Users\mayan\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
        "wmic CPU Get NumberOfCores /Format:csv".split(),
        capture_output=True,
        text=True,
    )
  File "c:\Users\mayan\anaconda3\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\mayan\anaconda3\Lib\subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\mayan\anaconda3\Lib\subprocess.py", line 1554, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                             # no special security
                             ^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                             cwd,
                             ^^^^
                             startupinfo)
                             ^^^^^^^^^^^^

KNN Model
Precision:  0.6759751100318713
Recall:  0.5413693111770936
F1 score:  0.6012303064195769
Accuracy:  0.7880815740930519
CM:  [[122624  14945]
 [ 26413  31178]]

In [13]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)

y_pred = nb_model.predict(X_test_scaled)

# Evaluation
print("Naive Bayes Model")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("F1 score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("CM: ", confusion_matrix(y_test, y_pred))

Naive Bayes Model
Precision:  0.5106821374681305
Recall:  0.8521123092149815
F1 score:  0.6386268105097407
Accuracy:  0.7154232424677188
CM:  [[90548 47021]
 [ 8517 49074]]

# Feature Engineering|

In [14]:

# df["Applicant_Income_log"] = np.log1p(df["Applicant_Income"])

X = df.drop(columns=["Loan_Approved"])
y = df["Loan_Approved"]

# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [15]:
X_train.head()

,Applicant_Income,Coapplicant_Income,Age,Dependents,Existing_Loans,Savings,Loan_Amount,Loan_Term,Education_Level,Employment_Status_Salaried,...,Property_Area_Semiurban,Property_Area_Urban,Gender_Male,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed,Collateral_Ratio,DTI_Ratio_sq,Credit_Score_sq
864624,16700.0,11100.0,33.0,2.0,2.0,3700.0,1300000.0,24.0,1,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.692307,0.090601,448900.0
621468,40300.0,12600.0,27.0,2.0,2.0,38800.0,256000.0,60.0,1,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.835934,0.235225,327184.0
600263,322000.0,162000.0,43.0,0.0,0.0,343900.0,13440000.0,84.0,0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.742634,0.028900,375769.0
424819,65200.0,100.0,37.0,2.0,2.0,5300.0,406000.0,24.0,1,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2.105906,0.084681,351649.0
344070,116200.0,57900.0,41.0,1.0,3.0,534200.0,622000.0,36.0,0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,2.451765,0.152100,483025.0

In [16]:
# Logistic regression

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

log_model = LogisticRegression()
log_model.fit(X_train_scaled, y_train)

y_pred = log_model.predict(X_test_scaled)

# Evaluation
print("Logistic Regression Model")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("F1 score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("CM: ", confusion_matrix(y_test, y_pred))

Logistic Regression Model
Precision:  0.7478846347100794
Recall:  0.6461252626278412
F1 score:  0.6932908538743875
Accuracy:  0.8312973970075835
CM:  [[125025  12544]
 [ 20380  37211]]

In [17]:
# KNN Not suitable for large number of features 

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)

y_pred = knn_model.predict(X_test_scaled)

# Evaluation
print("KNN Model")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("F1 score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("CM: ", confusion_matrix(y_test, y_pred))

KNN Model
Precision:  0.6585212901607475
Recall:  0.5470125540449029
F1 score:  0.5976097884852509
Accuracy:  0.7826193892191022
CM:  [[121233  16336]
 [ 26088  31503]]

In [18]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)

y_pred = nb_model.predict(X_test_scaled)

# Evaluation
print("Naive Bayes Model")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("F1 score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("CM: ", confusion_matrix(y_test, y_pred))

Naive Bayes Model
Precision:  0.5106821374681305
Recall:  0.8521123092149815
F1 score:  0.6386268105097407
Accuracy:  0.7154232424677188
CM:  [[90548 47021]
 [ 8517 49074]]

In [19]:
# Decision Tree Classifier

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Create Decision Tree model
dt_model = DecisionTreeClassifier(
    random_state=42,
    max_depth=5
)

# Train on unscaled data
dt_model.fit(X_train, y_train)

# Prediction
y_pred = dt_model.predict(X_test)

# Evaluation
print("Decision Tree Model")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("F1 score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("CM: ")
print(confusion_matrix(y_test, y_pred))

Decision Tree Model
Precision:  0.7091898540730939
Recall:  0.6607456026115192
F1 score:  0.6841111750323602
Accuracy:  0.8199323631891781
CM:
[[121965  15604]
 [ 19538  38053]]

In [22]:
results = []

for depth in [3, 5, 7, 10, 15, 20, None]:
    m = DecisionTreeClassifier(
        max_depth=depth,
        min_samples_leaf=50,
        random_state=42
    )
    
    m.fit(X_train, y_train)
    
    train_pred = m.predict(X_train)
    test_pred = m.predict(X_test)
    
    train_acc = accuracy_score(y_train, train_pred)
    test_acc = accuracy_score(y_test, test_pred)
    f1 = f1_score(y_test, test_pred, zero_division=0)
    
    results.append({
        "depth": depth,
        "train_acc": train_acc,
        "test_acc": test_acc,
        "f1": f1,
        "model": m
    })
    
    print(
        f"depth={str(depth):>4} | "
        f"train acc={train_acc:.4f} | "
        f"test acc={test_acc:.4f} | "
        f"F1={f1:.4f}"
    )


# Find the best tree based on F1 score
best_result = max(results, key=lambda x: x["f1"])

best_depth = best_result["depth"]
dt_model = best_result["model"]

print("\nBest Decision Tree")
print("Best depth:", best_depth)
print("Train Accuracy:", round(best_result["train_acc"], 4))
print("Test Accuracy :", round(best_result["test_acc"], 4))
print("F1 Score      :", round(best_result["f1"], 4))


# Feature importance
importances = pd.Series(
    dt_model.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

print("\nTop 10 features:")
print(importances.head(10))

depth=   3 | train acc=0.7917 | test acc=0.7909 | F1=0.5956
depth=   5 | train acc=0.8204 | test acc=0.8199 | F1=0.6841
depth=   7 | train acc=0.8425 | test acc=0.8403 | F1=0.7192
depth=  10 | train acc=0.8701 | test acc=0.8634 | F1=0.7547
depth=  15 | train acc=0.8880 | test acc=0.8706 | F1=0.7735
depth=  20 | train acc=0.8891 | test acc=0.8702 | F1=0.7733
depth=None | train acc=0.8891 | test acc=0.8702 | F1=0.7734

Best Decision Tree
Best depth: 15
Train Accuracy: 0.888
Test Accuracy : 0.8706
F1 Score      : 0.7735

Top 10 features:
Credit_Score_sq                 0.247142
Loan_Amount                     0.226108
DTI_Ratio_sq                    0.189604
Applicant_Income                0.118711
Existing_Loans                  0.083327
Collateral_Ratio                0.076788
Savings                         0.031618
Employment_Status_Salaried      0.009649
Employment_Status_Unemployed    0.008975
Education_Level                 0.003185
dtype: float64